import type { Metadata } from "next";
import { Roboto_Slab, Poppins, Shrikhand } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";

export const poppins: NextFontWithVariable = Poppins({
    subsets: ['latin'],
    weight: '400',
    variable: '--font-poppins',
    display: 'swap',
})

export const roboto_slab: NextFontWithVariable = Roboto_Slab({
    subsets: ['latin'],
    weight: ['400','700'],
    variable: '--font-roboto-slab',
    display: 'swap',
})

export const shrikhand: NextFontWithVariable = Shrikhand({
    subsets: ['latin'],
    weight: '400',
    variable: '--font-shrikhand',
    display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto_slab.variable} ${shrikhand.variable}`}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
