import type { Metadata } from "next";
import { Roboto_Slab, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
    subsets: ['latin'],
    weight: '700',
    variable: '--font-poppins',
    display: 'swap',
})

const roboto_slab = Roboto_Slab({
    subsets: ['latin'],
    weight: '400',
    variable: '--font-roboto-slab',
    display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto_slab.variable}`}>{children}</body>
    </html>
  );
}
